services:
  server:
    build: ./server
    ports:
      - "8000:8000"
      # remove in PROD
    volumes:
      - ./server:/server
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - server
